(()=>{if(window.__agenttrapObserver)return;window.__agenttrapObserver=true;let last='',lastTime=0;const bypass=new WeakSet(),pending=new WeakSet();
const hash=async bytes=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');
const signals=text=>[...(/(?:api[_ -]?key|password|secret|token)\s*[:=]\s*\S{6,}|sk-[a-z0-9_-]{12,}/i.test(text)?['Credential pattern']:[]),...(/ignore (?:all |previous |the )*instructions|bypass (?:the )?(?:policy|safeguards)/i.test(text)?['Prompt manipulation signal']:[]),...(/[\w.+-]+@[\w.-]+\.[a-z]{2,}/i.test(text)?['Email address']:[])];
const redact=text=>text.replace(/sk-[a-z0-9_-]+|(?:password|secret|token|api[_ -]?key)\s*[:=]\s*\S+/gi,'[REDACTED]').replace(/[\w.+-]+@[\w.-]+\.[a-z]{2,}/gi,'[EMAIL]').slice(0,160);
const note=text=>{let n=document.getElementById('agenttrap-protection-status');if(!n){n=document.createElement('div');n.id='agenttrap-protection-status';n.setAttribute('role','alert');n.style.cssText='position:fixed;bottom:24px;right:24px;z-index:2147483647;max-width:420px;padding:18px;background:#09223b;color:white;border:2px solid #55dde4;border-radius:12px;font:15px/1.5 system-ui';document.documentElement.append(n);}n.textContent='AgentTrap: '+text;setTimeout(()=>n.remove(),9000);};
const send=event=>chrome.runtime.sendMessage({action:'event',event}).catch(()=>{});
const check=async event=>{const r=await chrome.runtime.sendMessage({action:'check',event});if(!r?.ok)throw Error(r?.error||'Risk checker unavailable');return r;};
async function hold(e,key,eventPromise,resume){e.preventDefault();e.stopImmediatePropagation();if(pending.has(key))return;pending.add(key);try{const payload=await eventPromise();const result=payload.__decision||await check(payload);if(result.allowed){if(result.monitoring!==false)note('Checked: '+result.decision+' · risk '+result.risk);resume();}else{note('Submission blocked · risk '+result.risk+' reaches company threshold '+result.threshold+'. Review this content in your CRM.');if(key.type==='file')key.value='';}}catch(error){note('Submission held: '+error.message+'. Keep your CRM open, sign in, and check your connection.');if(key.type==='file')key.value='';}finally{pending.delete(key);}}
const consume=key=>{if(bypass.has(key)){bypass.delete(key);return true;}return false;};
const promptEvent=async element=>{const text=(element.value||element.innerText||'').trim();if(text.length>1000000)throw Error('Prompt exceeds the monitoring size limit');return{kind:'prompt_submit_intent',characters:text.length,fingerprint:await hash(new TextEncoder().encode(text)),signals:signals(text),preview:redact(text)};};
const editable=e=>e?.matches?.('textarea,[contenteditable=true],[role=textbox]')&&e.type!=='password'&&e.type!=='email';
const inputFor=form=>form?.querySelector('textarea,[contenteditable=true],[role=textbox]')||document.querySelector('#prompt-textarea,textarea,[contenteditable=true][role=textbox]');
const selector='button[type=submit],button[data-testid*=send],button[aria-label*=Send],button[aria-label*=send]';
document.addEventListener('submit',e=>{if(consume(e.target))return;const element=inputFor(e.target);if(!editable(element)||(element.value||element.innerText||'').trim()==='')return;hold(e,e.target,()=>promptEvent(element),()=>{bypass.add(e.target);e.target.requestSubmit(e.submitter||undefined);queueMicrotask(()=>bypass.delete(e.target));});},true);
document.addEventListener('keydown',e=>{if(e.key!=='Enter'||e.shiftKey||e.isComposing||!editable(e.target))return;const element=e.target;if(!(element.value||element.innerText||'').trim())return;hold(e,element,()=>promptEvent(element),()=>{const form=element.closest('form'),button=form?.querySelector(selector)||document.querySelector(selector);if(button){bypass.add(button);if(form)bypass.add(form);button.click();queueMicrotask(()=>{bypass.delete(button);if(form)bypass.delete(form);});}else if(form){bypass.add(form);form.requestSubmit();queueMicrotask(()=>bypass.delete(form));}else note('Content passed the risk check. Use the website send control to submit.');});},true);
document.addEventListener('click',e=>{const button=e.target.closest?.(selector);if(!button||consume(button))return;const form=button.closest('form'),element=inputFor(form);if(!editable(element)||!(element.value||element.innerText||'').trim())return;hold(e,button,()=>promptEvent(element),()=>{bypass.add(button);if(form)bypass.add(form);button.click();queueMicrotask(()=>{bypass.delete(button);if(form)bypass.delete(form);});});},true);
document.addEventListener('change',e=>{const input=e.target;if(input.type!=='file'||consume(input)||!input.files?.length)return;const files=Array.from(input.files);hold(e,input,async()=>{let lastResult={allowed:true,monitoring:false};for(const file of files){if(file.size>10*1024*1024)throw Error('Files above 10 MB cannot be checked; this upload is held');const event={kind:'file_selected',fileName:file.name,fileSize:file.size,fingerprint:await hash(await file.arrayBuffer()),signals:[]};const result=await check(event);lastResult=result;if(!result.allowed)throw Error('File blocked at risk '+result.risk+' / threshold '+result.threshold);}return {__decision:lastResult};},()=>{bypass.add(input);input.dispatchEvent(new Event('change',{bubbles:true}));});},true);
document.addEventListener('paste',async e=>{if(!editable(e.target))return;const text=e.clipboardData?.getData('text/plain');if(text&&text.length<=1000000){const fingerprint=await hash(new TextEncoder().encode(text));if(last===fingerprint&&Date.now()-lastTime<1500)return;last=fingerprint;lastTime=Date.now();send({kind:'paste_observed',characters:text.length,fingerprint,signals:signals(text),preview:redact(text)});}},true);
})();
