'use strict';
const statusNode=document.getElementById('status');
function status(message,type='info'){statusNode.textContent=message;statusNode.dataset.state=type;statusNode.scrollIntoView?.({block:'nearest'});}
function indicator(id,text,success=false){const el=document.getElementById(id);el.textContent=text;el.classList.toggle('complete',success);}
async function call(action,data={}){const r=await chrome.runtime.sendMessage({action,...data});if(!r?.ok)throw Error(r?.error||'Companion unavailable');return r;}
function explain(error){const text=error.message||String(error);return /fetch|network|timeout/i.test(text)?'Cannot reach the desktop CRM. Keep the Full CRM open on this laptop, sign in, and generate a fresh pairing code. '+text:text;}
let busy=false;
document.getElementById('pair').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;const button=e.target.querySelector('button');button.disabled=true;status('Connecting to your desktop CRM…');try{await call('pair',{code:document.getElementById('code').value.trim()});document.getElementById('code').value='';indicator('pair-state','✓ CRM paired successfully',true);status('SUCCESS — Paired with your Full CRM. Now select websites, tick consent, and click Grant access & enable.','success');}catch(error){indicator('pair-state','Pairing needs attention');status(explain(error),'error');}finally{busy=false;button.disabled=false;}});
document.getElementById('sites').addEventListener('invalid',e=>{if(e.target.id==='consent')status('Tick the monitoring consent checkbox before enabling website access.','error');},true);
document.getElementById('sites').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;const button=e.target.querySelector('button');button.disabled=true;try{const hosts=Array.from(document.querySelectorAll('#sites input[type=checkbox][value]:checked')).map(x=>x.value);let internal=null;const text=document.getElementById('internal').value;if(text){const u=new URL(text);if(u.protocol!=='https:'||u.username||u.password)throw Error('Use your internal AI HTTPS origin.');internal=u.hostname;hosts.push(internal);}if(!hosts.length)throw Error('Select at least one website.');if(!document.getElementById('consent').checked)throw Error('Monitoring consent is required.');const origins=hosts.map(h=>'https://'+h+'/*');const granted=await chrome.permissions.request({origins});if(!granted)throw Error('Website permissions were not granted.');status('Enabling your approved websites…');await call('enable',{hosts,internal});indicator('site-state','✓ Website observation enabled',true);status('SUCCESS — Extension enabled for '+hosts.join(', ')+'. Final step: tick monitoring consent and Enable monitoring inside the CRM, then reload your AI page.','success');}catch(error){indicator('site-state','Website observation not enabled');status(explain(error),'error');}finally{busy=false;button.disabled=false;}});
document.getElementById('pause').addEventListener('click',async()=>{try{await call('pause');indicator('site-state','Website observation paused');status('Paused. Approved website access was revoked.');}catch(error){status(explain(error),'error');}});
chrome.storage.local.get(['hosts','enabled','internal','token']).then(data=>{for(const input of document.querySelectorAll('#sites input[value]'))input.checked=data.hosts?.includes(input.value)||false;document.getElementById('internal').value=data.internal?'https://'+data.internal:'';indicator('pair-state',data.token?'Pairing saved · valid only for the same CRM session':'CRM not paired');indicator('site-state',data.enabled?'Website observation enabled':'Website observation paused',!!data.enabled);status(data.enabled?'Extension permissions are enabled. Keep the CRM open with monitoring enabled. Pair again if you restarted the CRM.':'Start by pairing with your running Full CRM.');}).catch(error=>status(explain(error),'error'));
