import fs from 'node:fs/promises';import path from 'node:path';
const root=process.cwd(),desktop=path.join(root,'desktop');await fs.mkdir(path.join(desktop,'ui'),{recursive:true});
let html=await fs.readFile('web/demo.html','utf8');html=html.replace('<script src="auth-bundle.js" defer></script>','<script src="account.js" defer></script><script src="desktop.js" defer></script><script src="enterprise.js" defer></script>').replace('<script src="trial.js" defer></script>','').replace('<body>','<body class="dark">');const gate=html.indexOf('<div id="trial-gate"');html=html.slice(0,gate)+'</body></html>';html=html.replace('href="index.html"','href="https://agenttrap-ai-governance.arceus6667.chatgpt.site/" target="_blank" rel="noopener"').replace('Enterprise preview','Desktop CRM').replace('Signed-in metadata is saved privately.','Metadata is saved locally on this device.').replace('Connecting workspace…','Opening local workspace…').replace('Demo terms & privacy','Desktop terms & privacy').replace('No live platform enforcement','Consent-based browser observations');
await fs.writeFile(path.join(desktop,'ui/demo.html'),html);
for(const name of ['style.css','favicon.svg'])await fs.copyFile('web/'+name,path.join(desktop,'ui',name));
await fs.copyFile(path.join(desktop,'desktop.js'),path.join(desktop,'ui/desktop.js'));await fs.copyFile(path.join(desktop,'account.js'),path.join(desktop,'ui/account.js'));await fs.copyFile('web/enterprise.js',path.join(desktop,'ui/enterprise.js'));
let app=await fs.readFile('web/app.js','utf8');app=app.replaceAll('Saved to your private workspace','Saved locally on this device').replaceAll('Loading your private workspace…','Loading your local workspace…').replaceAll('Private workspace ready','Local workspace ready').replaceAll('Cloud save failed','Local save failed').replace('No external platform action was performed.','No external platform action was performed.').replace('Provider accounts are not connected.','Use AI pairing & alerts to enable approved browser observations.').replace('Account-private Supabase database','Local device metadata database').replace('Supabase authentication with Google and email','Verified company account; local CRM plus tenant audit storage');await fs.writeFile(path.join(desktop,'ui/app.js'),app);
const readme=await fs.readFile(path.join(desktop,'README.md'),'utf8');await fs.writeFile(path.join(desktop,'ui/terms.html'),'<!doctype html><html><head><meta charset="utf-8"><title>Desktop privacy & evaluation terms</title><link rel="stylesheet" href="style.css"></head><body class="dark"><main style="max-width:900px;margin:auto;padding:40px"><h1>Desktop evaluation terms & privacy</h1><pre style="white-space:pre-wrap;font:16px/1.7 Arial">'+readme.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')+'</pre><a href="demo.html">Return to CRM</a></main></body></html>');
if(process.argv.includes('--prepare')){console.log('Prepared desktop UI');process.exit();}
// Dependency-free ZIP writer using stored entries, suitable for reproducible small portable packages.
const table=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
function crc(bytes){let c=0xffffffff;for(const b of bytes)c=table[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
function zip(entries){let offset=0,parts=[],central=[];for(const {name,bytes,executable}of entries){const n=Buffer.from(name),h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(0x800,6);h.writeUInt32LE(crc(bytes),14);h.writeUInt32LE(bytes.length,18);h.writeUInt32LE(bytes.length,22);h.writeUInt16LE(n.length,26);parts.push(h,n,bytes);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(0x0314,4);c.writeUInt16LE(20,6);c.writeUInt16LE(0x800,8);c.writeUInt32LE(crc(bytes),16);c.writeUInt32LE(bytes.length,20);c.writeUInt32LE(bytes.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(((executable?0o100755:0o100644)<<16)>>>0,38);c.writeUInt32LE(offset,42);central.push(c,n);offset+=h.length+n.length+bytes.length;}const end=Buffer.alloc(22),directory=Buffer.concat(central);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...parts,directory,end]);}
async function files(directory,prefix=''){let result=[];for(const item of await fs.readdir(directory,{withFileTypes:true})){if(['node_modules','release','package-lock.json','package.json','main.cjs','edition.json'].includes(item.name))continue;const name=prefix+item.name,location=path.join(directory,item.name);if(item.isDirectory())result.push(...await files(location,name+'/'));else result.push({name,bytes:await fs.readFile(location),executable:item.name.endsWith('.sh')});}return result;}
const common=await files(desktop),companion=await files(path.join(root,'extension'),'browser-companion/');await fs.mkdir('web/downloads',{recursive:true});const manifest=[];
for(const edition of ['trial','full']){const entries=[...common,{name:'edition.json',bytes:Buffer.from(JSON.stringify({edition,license:'Hackathon evaluation only. Not a paid commercial license.'}))},...(edition==='full'?companion:[])];const bytes=zip(entries),name='AgentTrap-'+edition+'-portable.zip';await fs.writeFile('web/downloads/'+name,bytes);manifest.push({edition,name,url:'/downloads/'+name,size:bytes.length,format:'Portable ZIP',requires:'Node.js 24+'});}
const extensionZip=zip(await files(path.join(root,'extension')));await fs.writeFile('web/downloads/AgentTrap-browser-companion.zip',extensionZip);await fs.writeFile('web/downloads-manifest.json',JSON.stringify(manifest));console.log('Packaged Trial, Full Hackathon, and browser companion downloads');
