'use strict';
(async()=>{
const desktop=!!window.AgentTrapDesktop;
if(desktop)await window.AgentTrapAuth.ready;else await window.AgentTrapAuth.ready;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let me=null,company=null,data=null,busy=false;
const call=async(action,payload={})=>{if(desktop)return window.AgentTrapDesktop.api('account/rpc',{action,payload});const r=await fetch('/api/enterprise',{method:'POST',headers:{'Content-Type':'application/json',...await window.AgentTrapAuth.headers()},body:JSON.stringify({action,payload})});const d=await r.json();if(!r.ok)throw Error(d.error||'Company request failed');return d;};
const head=`<div class="page-head"><div><div class="eyebrow">VERIFIED COMPANY WORKSPACE</div><h1>Enterprise accounts & security</h1><p>Verified identities, explicit team membership, and consented audit observations.</p></div></div>`;
const show=(text,error=false)=>{const el=document.getElementById('enterprise-message');if(el){el.textContent=text;el.style.color=error?'#ff8795':'#70e2dc';}};
function content(){
if(!window.AgentTrapAuth.session)return head+'<div class="card"><h2>Register or sign in first</h2><p>Use your company email to verify your identity.</p><a class="btn primary" href="signin.html">Verify email / sign in</a></div>';
const admin=company&&['owner','admin'].includes(company.role);const events=data?.events||[];const high=events.filter(e=>e.risk>=company?.threshold).length;
return head+`<p id="enterprise-message" role="status"></p><div class="card"><h2>Your verified identity</h2><p>${escape(me?.profile?.full_name||'Complete your profile')} · ${escape(me?.email||'')}</p><p class="note">Email verification proves access to this mailbox. Company domain ownership: ${company?.ownership_verified?'DNS control verified':'pending DNS verification'}.</p><form id="enterprise-profile"><label>Full name<input name="name" required minlength="2" maxlength="120" value="${escape(me?.profile?.full_name||'')}"></label><button class="btn">Save profile</button></form>${desktop?'<button class="btn" id="enterprise-logout" style="margin-top:16px">Sign out</button>':''}</div>`+
(!company?`<div class="grid2 grid-equal" style="margin-top:20px"><div class="card"><h2>Create your company workspace</h2><p class="note">Your verified business email domain becomes the workspace domain. Existing company domains require an administrator invitation. A seven-day hackathon evaluation is granted; this is not a paid license.</p><form id="enterprise-create"><label>Company name<input name="name" required minlength="2" maxlength="160"></label><button class="btn primary">Create workspace</button></form></div><div class="card"><h2>Join your company</h2><p class="note">Your admin must invite your exact verified email. Ask them for the one-time invitation code.</p><form id="enterprise-join"><label>Invitation code<input name="code" required autocomplete="off"></label><button class="btn primary">Accept invitation</button></form></div></div>`:
`<div class="card" style="margin-top:20px"><h2>${escape(company.name)}</h2><p>${escape(company.domain)} · ${escape(company.role)} · Workspace ID: <span class="mono">${escape(company.id)}</span></p><p>License: ${escape(company.license?.plan)} / ${escape(company.license?.status)} · ${company.license?.expires_at?'Expires '+escape(company.license.expires_at):'No scheduled expiry'}</p><p class="note">A paid license is issued only by the operator after verifying the payment reference. Downloading the Full installer does not prove a ₹90,000 payment.</p>${company.role==='owner'&&!company.ownership_verified?`<p class="note">To verify domain control, add DNS TXT record <b>_agenttrap-verify.${escape(company.domain)}</b> with value <b>agenttrap-company=${escape(company.id)}</b>.</p><button class="btn" id="enterprise-verify-domain">Verify DNS domain control</button>`:''}<div class="actions"><button class="btn" id="enterprise-refresh">Refresh records</button><button class="btn" id="enterprise-export">Export visible company evidence</button></div></div>`+
`<div class="grid2 grid-equal" style="margin-top:20px"><div class="card"><h2>Company activity overview</h2><p>${events.length} recent observations · ${high} above threshold ${company.threshold}</p><p class="note">View covers up to 500 recent records. Observed risks are deterministic rule estimates, not the probability of a breach. Only paired, consenting devices report activity while their CRM is running.</p><p>Pre-send blocking: <b>${company.block_enabled?'Enabled':'Disabled'}</b></p></div><div class="card"><h2>Members</h2>${(data?.members||[]).map(m=>`<p>${escape(m.name||m.email)} · ${escape(m.email)} · ${escape(m.role)} · ${m.active?'active':'revoked'} ${admin&&m.userId!==me.userId&&m.role!=='owner'?`<button class="btn" data-remove-member="${escape(m.userId)}">Revoke access</button>`:''}</p>`).join('')}</div></div>`+
(admin?`<div class="grid2 grid-equal" style="margin-top:20px"><div class="card"><h2>Add company accounts</h2><form id="enterprise-invite"><label>Company email<input name="email" required type="email"></label><label>Role<select name="role"><option value="member">Member</option>${company.role==='owner'?'<option value="admin">Admin</option>':''}</select></label><button class="btn primary">Create invitation</button></form><p class="note">Share the displayed one-time code securely. The recipient must verify that exact email, accept the invitation and consent on their own device. No invitation email is sent automatically.</p><p id="enterprise-invite-code" class="mono" role="status"></p></div><div class="card"><h2>Risk threshold & browser protection</h2><form id="enterprise-policy"><label>Risk threshold (25–100)<input name="threshold" type="number" min="25" max="100" required value="${company.threshold}"></label><label><input name="blockEnabled" type="checkbox" ${company.block_enabled?'checked':''}>Hold observed prompt/file submission when risk reaches this threshold</label><button class="btn primary">Save company boundary</button></form><p class="note">Applies to intercepted submission controls on approved browser pages. Background requests, other devices/apps, and provider-side retention are not stopped. When protection is enabled and the local/cloud checker is unavailable, intercepted actions are held. Test with synthetic data first.</p></div></div>`:'')+
`<div class="card" style="margin-top:20px"><h2>Activity and risk records</h2><div class="table-wrap"><table><thead><tr><th>User / time</th><th>AI platform / observation</th><th>Evidence</th><th>Risk / decision</th></tr></thead><tbody>${events.map(e=>`<tr><td>${escape(data.members.find(m=>m.userId===e.actor_id)?.email||e.actor_id)}<small>${escape(e.occurred_at)}</small></td><td>${escape(e.event.provider)}<small>${escape(e.event.kind)}</small></td><td>${escape(e.event.preview||e.event.fileName||'Fingerprint only')}<small class="mono">${escape(e.event.fingerprint||'Metadata only')}</small></td><td>${e.risk} / ${escape(e.action)}</td></tr>`).join('')}</tbody></table></div>${!events.length?'<p class="note">No activity received yet. Pair a member device and enable explicit monitoring consent.</p>':''}</div>`+
(admin?`<div class="card" style="margin-top:20px"><h2>Administrative audit</h2>${(data.adminEvents||[]).map(e=>`<p>${escape(e.created_at)} · ${escape(e.action)} · ${escape(JSON.stringify(e.detail))}</p>`).join('')||'<p>No administrative changes yet.</p>'}</div>`:''));
}
let target=document.getElementById('enterprise-root'),hooks=null;
async function load(){if(window.AgentTrapAuth.session){me=await call('me');const selected=desktop?window.AgentTrapAccount.state?.companyId:null;company=me.companies.find(c=>c.id===selected)||me.companies[0]||null;data=company?await call('dashboard',{companyId:company.id}):null;}if(desktop&&location.hash==='#enterprise')hooks.render();else if(!desktop)target.innerHTML=content();}
if(desktop){if(!window.AgentTrapConsole)await new Promise(r=>window.addEventListener('agenttrap-console-ready',r,{once:true}));hooks=window.AgentTrapConsole;hooks.labels.enterprise='Company accounts';hooks.renderers.enterprise=content;const nav=document.querySelector('.sidebar nav'),link=document.createElement('a');link.href='#enterprise';link.dataset.page='enterprise';link.textContent='Company accounts';nav.insertBefore(link,nav.lastElementChild);target=document.getElementById('main');if(!window.AgentTrapAccount.state?.companies?.length)location.hash='#enterprise';window.addEventListener('hashchange',()=>{if(location.hash==='#enterprise')load().catch(e=>show(e.message,true));});}
try{await load();}catch(e){if(!desktop)target.innerHTML=head+'<p id="enterprise-message"></p>';show(e.message,true);}
target.addEventListener('submit',async event=>{const form=event.target;if(!form.id.startsWith('enterprise-'))return;event.preventDefault();if(busy)return;busy=true;const button=form.querySelector('button');button.disabled=true;try{const p=Object.fromEntries(new FormData(form));let action=form.id.replace('enterprise-','');if(action==='create')action='create_company';if(action==='join')action='accept_invite';if(company)p.companyId=company.id;if(action==='policy'){p.threshold=Number(p.threshold);p.blockEnabled=form.elements.blockEnabled.checked;}const result=await call(action,p);if(action==='invite'){document.getElementById('enterprise-invite-code').textContent=result.code+' · valid for seven days';show('Invitation created. Share this code securely.');}else{await load();show('Saved to your company workspace.');}}catch(e){show(e.message,true);}finally{busy=false;button.disabled=false;}});
target.addEventListener('click',async event=>{try{const id=event.target.id;if(id==='enterprise-refresh')await load();if(id==='enterprise-verify-domain'){const r=await call('verify_domain',{companyId:company.id});await load();show(r.verified?'Company domain control verified by DNS.':r.message,!r.verified);}if(id==='enterprise-logout'){await window.AgentTrapAccount.call('logout',{});location.reload();}if(id==='enterprise-export'){const blob=new Blob([JSON.stringify({company,members:data.members,events:data.events,adminEvents:data.adminEvents},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='agenttrap-company-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(event.target.dataset.removeMember){await call('remove_member',{companyId:company.id,userId:event.target.dataset.removeMember});await load();show('Company access revoked.');}}catch(e){show(e.message,true);}});
let seen=new Set();setInterval(async()=>{if(!company||document.hidden||desktop&&location.hash!=='#enterprise')return;try{const next=await call('dashboard',{companyId:company.id});const alerts=next.events.filter(e=>e.risk>=company.threshold&&!seen.has(e.id));seen=new Set(next.events.map(e=>e.id));data=next;if(!document.activeElement?.closest('form')){if(desktop)hooks.render();else target.innerHTML=content();}if(alerts.length)show(alerts.length+' new high-risk company observations. Review the activity log.');}catch(e){show(e.message,true);}},15000);
})();
