'use strict';
(()=>{
const h=window.AgentTrapConsole;if(!h)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const scenarios={
 training:{name:'Confidential file → external AI training',classification:'Confidential',purpose:'Model training',provenance:'Verified',text:'Synthetic confidential company report.',target:'External model-training endpoint',kind:'policy'},
 secret:{name:'Credential in a prompt',classification:'Internal',purpose:'Code assistance',provenance:'Verified',text:'password=synthetic_test_only_12345',target:'Approved AI prompt input',kind:'policy'},
 downstream:{name:'Hypothetical onward transfer by a provider',classification:'Confidential',purpose:'Summarization',provenance:'Verified',text:'Synthetic planning report.',target:'unapproved-recipient.example',kind:'downstream'},
 changed:{name:'Modified file needs human approval',classification:'Internal',purpose:'Summarization',provenance:'Modified',text:'Synthetic modified company memo.',target:'Approved AI prompt input',kind:'policy'},
 safe:{name:'Public document → internal AI',classification:'Public',purpose:'Internal analysis',provenance:'Verified',text:'Public release notes for an open-source library.',target:'Internal AI workspace',kind:'policy'},
 offline:{name:'Checker unavailable → hold submission',classification:'Internal',purpose:'Summarization',provenance:'Verified',text:'Synthetic company memo.',target:'Approved AI prompt input',kind:'offline'}
};
let employees=[{id:'DEMO-01',name:'Asha Mehta',department:'Finance',role:'Member'},{id:'DEMO-02',name:'Rohan Shah',department:'Engineering',role:'Member'},{id:'DEMO-03',name:'Neha Rao',department:'Security',role:'Admin'}];
let runs=[],current=null,timer=null,message='',realRoster=null;
try{const saved=JSON.parse(sessionStorage.getItem('agenttrap-simulation-v1'));if(saved?.employees?.length&&saved.employees.length<=50)employees=saved.employees;if(Array.isArray(saved?.runs))runs=saved.runs.slice(-50);}catch{}
const persist=()=>{try{sessionStorage.setItem('agenttrap-simulation-v1',JSON.stringify({employees,runs}));}catch{}};
const pill=a=>`<span class="pill ${a==='BLOCK'?'block':a==='ALLOW'?'allow':a==='MONITOR'?'monitor':'approval'}">${esc(a.replaceAll('_',' '))}</span>`;
const refresh=()=>{if(location.hash==='#simulation')h.render();};
function plan(input){
 const s=scenarios[input.scenario];const platform=input.scenario==='safe'?'Internal AI':input.platform;
 const result=h.evaluate({...s,platform,role:'Employee',coverage:1},h.state.policies,{...h.state.settings,threshold:input.threshold});
 let action=result.action,risk=result.risk,reason=result.reason;
 if(s.kind==='downstream'){risk=95;action=input.block?'BLOCK':'MONITOR';reason='Fictional gateway evidence identifies an unapproved destination. The browser companion cannot see provider-internal onward transfers.';}
 if(s.kind==='offline'){risk=null;action=input.block?'BLOCK':'APPROVAL_REQUIRED';reason='In this exercise the checker is unavailable. Hold an intercepted submission when protection is enabled.';}
 if(!input.block&&action==='BLOCK'){action='MONITOR';reason+=' Simulation enforcement is switched off; the exercise records an alert without a hold.';}
 const employee=employees.find(e=>e.id===input.employee);const fingerprint='SIMULATED-FINGERPRINT-'+Date.now();
 const steps=[
 {title:'Employee action',detail:`${employee.name} selects synthetic-${input.scenario}.txt for ${platform}. No file or prompt is sent.`,type:'info'},
 {title:'TraceSeal evidence',detail:`${s.provenance} provenance; placeholder ${fingerprint}. Real TraceSeal uses SHA-256 of actual file bytes.`,type:'info'},
 {title:s.kind==='downstream'?'Hypothetical gateway event':'Browser interception',detail:s.kind==='downstream'?`Fictional provider → ${s.target} event supplied by this simulator. A real gateway/provider log would be needed to substantiate it.`:`Simulated observation from ${platform} with classification ${s.classification}; purpose ${s.purpose}.`,type:'info'},
 {title:'Policy decision',detail:`${action} · ${risk===null?'risk unavailable':`risk ${risk}/100`} · threshold ${input.threshold}. ${reason}`,type:action==='ALLOW'?'safe':'alert'},
 {title:'Containment response',detail:action==='BLOCK'?(s.kind==='downstream'?'Hypothetical gateway stops this modeled outbound request and isolates this simulated connector. It cannot recall data already released.':'Simulated submission held before send. An actual companion can hold only supported intercepted controls on approved pages.'):(action==='APPROVAL_REQUIRED'?'Submission waits for a simulated administrator review.':'Simulated request proceeds; no real provider action is performed.'),type:action==='BLOCK'?'alert':'info'},
 {title:'Alert and evidence',detail:action==='ALLOW'?'Informational evidence retained in this sandbox.':`Simulated desktop and phone alerts queued for ${employee.name}; nothing is delivered. Administrator reviews, acknowledges, and exports the exercise.`,type:action==='ALLOW'?'safe':'alert'}
 ];
 return{id:'SIM-'+Date.now(),timestamp:new Date().toISOString(),simulated:true,dryRun:true,employee:{...employee},scenario:input.scenario,platform,destination:s.target,threshold:input.threshold,enforcementEnabled:input.block,risk,action,reason,steps,completedSteps:0,status:'In progress',acknowledged:false,fingerprint};
}
function step(){if(!current||current.completedSteps===current.steps.length)return;current.completedSteps++;if(current.completedSteps===current.steps.length){current.status=current.action==='APPROVAL_REQUIRED'?'Awaiting simulated review':'Completed';runs.push(current);runs=runs.slice(-50);stop();persist();}refresh();}
function stop(){if(timer)clearInterval(timer);timer=null;}
function start(auto=false){stop();const form=document.getElementById('sim-controls');const input={employee:form.elements.employee.value,scenario:form.elements.scenario.value,platform:form.elements.platform.value,threshold:Number(form.elements.threshold.value),block:form.elements.block.checked};if(!Number.isFinite(input.threshold)||input.threshold<25||input.threshold>100)throw Error('Use a threshold from 25 to 100.');current=plan(input);message='Exercise started. Every event below is simulated.';if(auto){timer=setInterval(step,950);step();}refresh();}
function render(){
 const alerts=runs.filter(r=>r.action!=='ALLOW'&&!r.acknowledged);const visible=current?.steps.slice(0,current.completedSteps)||[];
 return `<div class="page-head"><div><div class="eyebrow">ADMINISTRATOR SANDBOX</div><h1>Data exposure simulation</h1><p>Rehearse detection, decisions, containment and employee incident review.</p></div><span class="pill approval">SIMULATION · NO LIVE ACTIONS</span></div><div class="notice"><b>Isolated exercise.</b> Synthetic employees and events do not change company policies, licenses, live logs or real permissions. Provider-internal transfers are hypothetical; the CRM cannot infer them from browser fingerprints.</div><div class="stats"><div class="stat"><span>Sandbox employees</span><strong>${employees.length}</strong><small>Fictional or locally added</small></div><div class="stat"><span>Completed exercises</span><strong>${runs.length}</strong><small>This browser tab</small></div><div class="stat"><span>Modeled holds</span><strong>${runs.filter(r=>r.action==='BLOCK').length}</strong><small>No real application stopped</small></div><div class="stat"><span>Unacknowledged alerts</span><strong>${alerts.length}</strong><small>Simulation only</small></div></div>
 <div class="grid2 grid-equal"><div class="card"><h2>Configure an exercise</h2><form id="sim-controls"><label>Employee<select name="employee">${employees.map(e=>`<option value="${esc(e.id)}">${esc(e.name)} · ${esc(e.department)} (${esc(e.role)})</option>`).join('')}</select></label><label>Scenario<select name="scenario">${Object.entries(scenarios).map(([id,s])=>`<option value="${id}">${esc(s.name)}</option>`).join('')}</select></label><label>AI system<select name="platform">${['ChatGPT','Claude','Gemini','Microsoft Copilot','Internal AI'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Exercise risk threshold (25–100)<input name="threshold" type="number" min="25" max="100" value="80" required></label><label class="trial-consent"><input name="block" type="checkbox" checked> Simulate automatic protection</label><div class="actions"><button class="btn primary" type="submit">Run animated exercise</button><button class="btn" type="button" id="sim-start">Start step by step</button></div></form><p class="note">Policy scenarios evaluate the current console rules. This threshold and protection switch affect only this exercise.</p></div><div class="card"><div class="card-head"><h2>Response timeline</h2><span class="pill muted">${current?current.completedSteps+'/6':'Ready'}</span></div><p id="sim-message" role="status" aria-live="polite">${esc(message||'Choose an employee and scenario to begin.')}</p><ol class="sim-timeline">${visible.map(s=>`<li class="${s.type}"><b>${esc(s.title)}</b><p>${esc(s.detail)}</p></li>`).join('')||'<li><b>Waiting for exercise</b><p>No simulated data transfer has started.</p></li>'}</ol>${current?`<div class="actions"><button class="btn" id="sim-next" ${current.completedSteps===6?'disabled':''}>Next step</button><button class="btn" id="sim-pause">Pause animation</button><button class="btn" id="sim-reset">Reset timeline</button></div>`:''}<p class="note">The alert step previews desktop and phone channels; it does not contact ntfy or send notifications.</p></div></div>
 <div class="card"><div class="card-head"><div><h2>Employee exposure overview</h2><p>Administrator view of this exercise roster</p></div><a class="btn" href="${window.AgentTrapDesktop?'#enterprise':'enterprise.html'}">Actual company members</a></div><div class="table-wrap"><table><thead><tr><th>Employee</th><th>Department / role</th><th>Exercises</th><th>Highest modeled risk</th><th>Most recent result</th></tr></thead><tbody>${employees.map(e=>{const r=runs.filter(r=>r.employee.id===e.id),last=r.at(-1);return `<tr><td><b>${esc(e.name)}</b><small>${esc(e.id)} · SANDBOX</small></td><td>${esc(e.department)} / ${esc(e.role)}</td><td>${r.length}</td><td>${r.some(x=>x.risk!==null)?Math.max(...r.map(x=>x.risk||0))+'/100':'—'}</td><td>${last?pill(last.action):'No exercise'}</td></tr>`;}).join('')}</tbody></table></div><form id="sim-add" class="sim-add"><label>Sandbox employee name<input name="name" required maxlength="100"></label><label>Department<input name="department" required maxlength="80"></label><label>Role<select name="role"><option>Member</option><option>Admin</option></select></label><button class="btn" type="submit">Add sandbox employee</button></form><p class="note">Adding a sandbox employee does not create an account or grant company access.</p></div>
 <div class="card sim-section"><div class="card-head"><div><h2>Actual company roster reference</h2><p>Read-only data from your existing company permissions</p></div><button class="btn" id="sim-roster">Load my company members</button></div>${realRoster?`<p>${esc(realRoster.company)} · ${realRoster.members.length} visible members</p><div class="table-wrap"><table><thead><tr><th>Member</th><th>Role</th><th>Access</th></tr></thead><tbody>${realRoster.members.map(m=>`<tr><td>${esc(m.name||m.email)}</td><td>${esc(m.role)}</td><td>${m.active?'Active':'Revoked'}</td></tr>`).join('')}</tbody></table></div>`:'<p>Load your visible company members, or use the fictional roster above. Company observations remain in Company accounts.</p>'}</div>
 <div class="card sim-section"><div class="card-head"><h2>Simulation incident ledger</h2><div class="actions"><button class="btn" id="sim-export">Export exercise evidence</button><button class="btn" id="sim-clear">Clear exercises</button></div></div><div class="table-wrap"><table><thead><tr><th>Time / employee</th><th>Scenario / destination</th><th>Decision</th><th>Admin response</th></tr></thead><tbody>${runs.slice().reverse().map(r=>`<tr><td>${esc(r.timestamp)}<small>${esc(r.employee.name)}</small></td><td>${esc(scenarios[r.scenario]?.name||r.scenario)}<small>${esc(r.destination)} · SIMULATED</small></td><td>${pill(r.action)}<small>${r.risk===null?'Risk unavailable':r.risk+'/100'}</small></td><td>${esc(r.status)}${!r.acknowledged?`<button class="btn small" data-sim-ack="${esc(r.id)}">Acknowledge</button>`:''}${r.status==='Awaiting simulated review'?`<button class="btn small" data-sim-review="${esc(r.id)}" data-result="Approved">Approve exercise</button><button class="btn small" data-sim-review="${esc(r.id)}" data-result="Rejected">Reject exercise</button>`:''}</td></tr>`).join('')||'<tr><td colspan="4">Complete an exercise to see its incident record.</td></tr>'}</tbody></table></div></div>`;
}
h.labels.simulation='Exposure simulation';h.renderers.simulation=render;
const nav=document.querySelector('.sidebar nav'),a=document.createElement('a');a.href='#simulation';a.dataset.page='simulation';a.textContent='Exposure simulation';nav.insertBefore(a,nav.querySelector('[data-page="docs"]'));
document.getElementById('main').addEventListener('submit',e=>{if(e.target.id==='sim-controls'){e.preventDefault();try{start(true);}catch(error){message=error.message;refresh();}}if(e.target.id==='sim-add'){e.preventDefault();if(employees.length>=50){message='Maximum 50 sandbox employees.';refresh();return;}const f=e.target.elements;employees.push({id:'DEMO-'+Date.now(),name:f.name.value.trim(),department:f.department.value.trim(),role:f.role.value});persist();message='Sandbox employee added. No real account was created.';refresh();}});
document.getElementById('main').addEventListener('click',async e=>{try{const id=e.target.id;if(id==='sim-start')start();if(id==='sim-next'){stop();step();}if(id==='sim-pause'){stop();message='Animation paused. Use Next step to continue.';refresh();}if(id==='sim-reset'){stop();current=null;message='Timeline reset. Completed exercises remain in the ledger.';refresh();}if(id==='sim-clear'){stop();current=null;runs=[];persist();message='Simulation incidents cleared. Live audit records were not changed.';refresh();}if(id==='sim-export'){const blob=new Blob([JSON.stringify({format:'AgentTrap simulation evidence v1',simulated:true,dryRun:true,claim:'Fictional exercise; no proof of provider-internal transfers or real blocking',employees,runs},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='agenttrap-simulation-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(id==='sim-roster'){await window.AgentTrapAuth.ready;let me,company,data;if(window.AgentTrapDesktop){me=await window.AgentTrapDesktop.api('account/rpc',{action:'me',payload:{}});company=me.companies.find(c=>c.id===window.AgentTrapAccount.state?.companyId)||me.companies[0];if(company)data=await window.AgentTrapDesktop.api('account/rpc',{action:'dashboard',payload:{companyId:company.id}});}else{const call=async(action,payload={})=>{const r=await fetch('/api/enterprise',{method:'POST',headers:{'Content-Type':'application/json',...await window.AgentTrapAuth.headers()},body:JSON.stringify({action,payload})});const d=await r.json();if(!r.ok)throw Error(d.error||'Company request failed');return d;};me=await call('me');company=me.companies[0];if(company)data=await call('dashboard',{companyId:company.id});}if(!company)throw Error('Create or join your company in Company accounts first.');realRoster={company:company.name,members:data.members};message='Company roster loaded read-only. Sandbox employees remain separate.';refresh();}if(e.target.dataset.simAck){const r=runs.find(r=>r.id===e.target.dataset.simAck);if(r){r.acknowledged=true;persist();refresh();}}if(e.target.dataset.simReview){const r=runs.find(r=>r.id===e.target.dataset.simReview);if(r){r.status='Simulated '+e.target.dataset.result;r.acknowledged=true;persist();refresh();}}}catch(error){message=error.message;refresh();}});
window.addEventListener('hashchange',()=>{if(location.hash!=='#simulation')stop();});
window.AgentTrapSimulation={scenarios,plan,get runs(){return runs;},get employees(){return employees;}};
if(location.hash==='#simulation')h.render();
})();
