'use strict';
(()=>{let trial=null,baseServer=0,baseClock=0,inFlight=null,lastGateState=null,unavailable=null;const allowed=new WeakSet();const pending=new WeakSet();const gate=document.getElementById('trial-gate'),body=document.getElementById('trial-body'),label=document.getElementById('trial-clock'),auth=document.getElementById('trial-auth');
const now=()=>baseServer+(performance.now()-baseClock);const active=()=>!!trial?.active&&now()<trial.expiresAt;
function update(data){unavailable=null;trial=data;baseServer=data.serverNow;baseClock=performance.now();window.AgentTrapTrialInfo=data;paint();}
function paint(){if(unavailable){showGate(unavailable);return;}if(!trial)return;const remaining=Math.max(0,Math.ceil((trial.expiresAt-now())/1000));label.textContent=trial.started?(trial.signedIn?'Signed in · ':'Guest · ')+String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0'):(trial.signedIn?'30-minute trial ready':'5-minute guest trial');label.classList.toggle('urgent',trial.started&&remaining<60);auth.innerHTML=trial.signedIn?'<button id="account-signout" class="trial-export">Sign out</button>':'<a href="/signin.html" target="_top">Sign in · 30 min</a>';document.getElementById('account-signout')?.addEventListener('click',()=>window.AgentTrapAuth.signOut().catch(e=>showGate(e.message)));if(active()){gate.hidden=true;lastGateState=null;document.getElementById('main').inert=false;document.querySelector('.shell').inert=false;document.querySelector('.sidebar').inert=false;}else{trial.active=false;showGate();}}
function showGate(message=''){if(message)unavailable=message;const signature=JSON.stringify([trial?.signedIn,trial?.started,message]);if(!gate.hidden&&lastGateState===signature)return;lastGateState=signature;gate.hidden=false;document.getElementById('main').inert=true;document.querySelector('.shell').inert=true;document.querySelector('.sidebar').inert=true;const signed=trial?.signedIn;const ended=trial?.started;body.innerHTML=`<div class="trial-emblem">A</div><div class="trial-kicker">AGENTTRAP ENTERPRISE DEMO</div><h1 id="trial-gate-title">${message?'Demo temporarily unavailable':ended?'Your '+(signed?'30':'5')+'-minute trial has ended.':signed?'Explore for thirty minutes.':'Your five-minute trial starts here.'}</h1><p>${message|| (ended?signed?'You have reached the end of your signed-in trial. You can export the evidence from this session and return to the product website.':'Sign in to unlock a separate thirty-minute trial. Your guest trial will not restart when you refresh.':'Analyze documents, verify TraceSeal fingerprints, create policies, review approvals, and inspect the audit trail.')}</p><div class="trial-inclusions"><span>Local document analysis</span><span>Deterministic decisions</span><span>TraceSeal evidence</span></div>${!ended&&!message?`<form id="trial-start"><label class="trial-consent"><input type="checkbox" required name="accepted"> <span>I have read the <a href="terms.html" target="_blank" rel="noopener">demo terms and privacy information</a>.</span></label><button class="btn primary" type="submit">Start ${signed?'30':'5'}-minute trial</button></form>`:''}${!signed&&!message?'<a class="trial-signin" href="/signin.html" target="_top">Sign in for 30 minutes</a>':''}${message?'<button class="btn" id="trial-retry">Try again</button>':''}<div class="trial-footer">${signed?'<button id="gate-signout" class="trial-export">Sign out</button>':''}<a href="index.html">Back to website</a><button id="expired-export" class="trial-export">Export session evidence</button><a href="terms.html" target="_blank" rel="noopener">Demo terms</a></div><p class="trial-small">No payment required. File contents stay in this browser. Signed-in CRM metadata is saved privately in Supabase. Trial timing and terms acknowledgement are stored on the server.</p>`;
 document.getElementById('gate-signout')?.addEventListener('click',()=>window.AgentTrapAuth.signOut().catch(e=>showGate(e.message)));const form=document.getElementById('trial-start');if(form)form.addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;button.textContent='Starting trial…';try{const r=await fetch('/api/trial/start',{method:'POST',headers:{'content-type':'application/json',...await window.AgentTrapAuth.headers()},body:JSON.stringify({accepted:true,termsVersion:trial.termsVersion})});const data=await r.json();if(!r.ok)throw new Error(data.error);update(data);if(data.signedIn)await window.AgentTrapCRM.save();}catch(error){showGate(error.message);}finally{button.disabled=false;}});document.getElementById('expired-export')?.addEventListener('click',()=>window.AgentTrapExport?.());document.getElementById('trial-retry')?.addEventListener('click',load);const title=document.getElementById('trial-gate-title');title.tabIndex=-1;title.focus();
}
async function load(){try{await window.AgentTrapAuth.ready;await window.AgentTrapCRM.ready;const r=await fetch('/api/trial/status',{cache:'no-store',headers:await window.AgentTrapAuth.headers()});const data=await r.json();if(!r.ok)throw new Error(data.error||'Trial service unavailable.');update(data);}catch(error){showGate(error.message);}}
async function authorize(){if(inFlight)return inFlight;inFlight=(async()=>{try{const r=await fetch('/api/trial/authorize',{method:'POST',headers:await window.AgentTrapAuth.headers()});const data=await r.json();if(data.serverNow)update(data);if(!r.ok){if(r.status===503)showGate(data.error);throw new Error(data.error||'Trial unavailable.');}return true;}finally{inFlight=null;}})();return inFlight;}
window.AgentTrapTrial={authorize,active};
document.addEventListener('submit',e=>{const form=e.target;if(!form.matches('#analysis-form,#verify-form,#new-policy,.approval-form,#settings-form'))return;if(allowed.has(form)){allowed.delete(form);return;}e.preventDefault();e.stopImmediatePropagation();if(pending.has(form))return;pending.add(form);const submitter=e.submitter;authorize().then(()=>{allowed.add(form);form.requestSubmit(submitter);}).catch(()=>{}).finally(()=>pending.delete(form));},true);
document.addEventListener('click',e=>{const button=e.target.closest('[data-action="sample"]');if(!button)return;if(allowed.has(button)){allowed.delete(button);return;}e.preventDefault();e.stopImmediatePropagation();if(pending.has(button))return;pending.add(button);authorize().then(()=>{allowed.add(button);button.click();}).catch(()=>{}).finally(()=>pending.delete(button));},true);
document.addEventListener('change',e=>{const input=e.target;if(!input.matches('[data-policy]'))return;if(allowed.has(input)){allowed.delete(input);return;}e.stopImmediatePropagation();const checked=input.checked;input.checked=!checked;authorize().then(()=>{allowed.add(input);input.checked=checked;input.dispatchEvent(new Event('change',{bubbles:true}));}).catch(()=>{});},true);
setInterval(()=>{if(trial){const wasActive=trial.active;if(wasActive&&!active())trial.expired=true;paint();}},1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});load();})();
