'use strict';
(()=>{
const session=new URLSearchParams(location.hash.slice(1)).get('session');if(session)sessionStorage.setItem('agenttrap-desktop-session',session);
const headers=()=>({'X-Desktop-Token':sessionStorage.getItem('agenttrap-desktop-session')||'','Content-Type':'application/json'});
const call=async(action,body)=>{const r=await fetch('/api/desktop/account/'+action,{method:body?'POST':'GET',headers:headers(),...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Account service failed');return d;};
let resolveReady;const ready=new Promise(resolve=>resolveReady=resolve);window.AgentTrapAccount={call,ready,state:null};
async function start(){const gate=document.createElement('div');gate.id='account-gate';gate.style.cssText='position:fixed;inset:0;background:#041429;z-index:10000;overflow:auto;display:grid;place-items:center;padding:24px';gate.innerHTML=`<div class="card" style="width:min(100%,540px)"><div class="eyebrow">AGENTTRAP AI · VERIFIED ACCESS</div><h1>Register or sign in</h1><p class="note">Use your company email. We email you a secure sign-in link. Open it on this laptop while the CRM stays open.</p><form id="desktop-account-form"><label>Access type<select id="account-mode"><option value="register">Register</option><option value="signin">Sign in</option></select></label><label id="name-label">Full name<input id="account-name" minlength="2" maxlength="120" required autocomplete="name"></label><label>Company email<input id="account-email" type="email" required autocomplete="email"></label><button class="btn primary">Send magic link</button></form><p id="account-message" role="status"></p><p class="note">An account is required for both desktop editions. Sessions stay in memory; sign in again after restarting. Email delivery must be configured by the operator. <a href="https://agenttrap-ai-governance.arceus6667.chatgpt.site/enterprise-setup.html" target="_blank" rel="noopener">Email setup guide</a></p></div>`;document.body.append(gate);
const message=(s,error=false)=>{const n=document.getElementById('account-message');n.textContent=s;n.style.color=error?'#ff8795':'#70e2dc';};let pending=false,email='',name='',cooldown=0;
const finish=state=>{window.AgentTrapAccount.state=state;gate.remove();resolveReady(state);};
document.getElementById('account-mode').onchange=e=>{const register=e.target.value==='register';document.getElementById('name-label').hidden=!register;document.getElementById('account-name').required=register;};
document.getElementById('desktop-account-form').onsubmit=async e=>{e.preventDefault();if(pending||Date.now()<cooldown)return;pending=true;const button=e.target.querySelector('button');button.disabled=true;try{email=document.getElementById('account-email').value.trim();name=document.getElementById('account-mode').value==='register'?document.getElementById('account-name').value.trim():'';await call('magic-link',{email,register:!!name,name});cooldown=Date.now()+60000;message('Check your email and click its sign-in link on this laptop. Keep this CRM open. Check spam if needed.');}catch(error){message(error.message,true);}finally{pending=false;button.disabled=false;}};
const poll=setInterval(async()=>{try{const state=await call('state');if(state.authenticated){clearInterval(poll);finish(state);}}catch{}},2000);
try{const state=await call('state');if(state.authenticated){clearInterval(poll);finish(state);}}catch(error){message(error.message,true);}
}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
