'use strict';
(()=>{
const session=new URLSearchParams(location.hash.slice(1)).get('session');if(session){sessionStorage.setItem('agenttrap-desktop-session',session);history.replaceState(null,'',location.pathname+'#dashboard');}
const headers=()=>({'X-Desktop-Token':sessionStorage.getItem('agenttrap-desktop-session')||''});
const api=async(path,body)=>{const r=await fetch('/api/desktop/'+path,{method:body?'POST':'GET',headers:{...headers(),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(data.error||'Local service unavailable');return data;};
window.AgentTrapDesktop={api,config:null};
window.AgentTrapAuth={session:null,headers:async()=>headers(),error:null};
window.AgentTrapAuth.ready=api('status').then(async config=>{window.AgentTrapDesktop.config=config;if(config.requireAccount){const account=await window.AgentTrapAccount.ready;window.AgentTrapAuth.session={user:{id:account.userId,email:account.email}};}else window.AgentTrapAuth.session={local:true};return window.AgentTrapAuth;}).catch(error=>{window.AgentTrapAuth.error=error.message;throw error;});
const accepted=new WeakSet(),pending=new WeakSet();
const notice=message=>{const n=document.getElementById('toast');n.textContent=message;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),5000);};
async function authorize(operation){await window.AgentTrapAuth.ready;return api('authorize',{operation});}
window.AgentTrapTrial={active:()=>true,authorize:()=>authorize('analysis')};
document.addEventListener('submit',event=>{const operations={'analysis-form':'analysis','verify-form':'integrity','new-policy':'policy','settings-form':'settings'};const form=event.target,operation=operations[form.id]||(form.matches('.approval-form')?'approval':null);if(!operation)return;if(accepted.has(form)){accepted.delete(form);return;}event.preventDefault();event.stopImmediatePropagation();if(pending.has(form))return;pending.add(form);const submitter=event.submitter;authorize(operation).then(()=>{accepted.add(form);form.requestSubmit(submitter);}).catch(e=>notice(e.message)).finally(()=>pending.delete(form));},true);
document.addEventListener('click',event=>{const button=event.target.closest('[data-action="sample"]');if(!button)return;if(accepted.has(button)){accepted.delete(button);return;}event.preventDefault();event.stopImmediatePropagation();if(pending.has(button))return;pending.add(button);authorize('analysis').then(()=>{accepted.add(button);button.click();}).catch(e=>notice(e.message)).finally(()=>pending.delete(button));},true);
document.addEventListener('change',event=>{if(!event.target.matches('[data-policy]'))return;if(!window.AgentTrapDesktop.config?.full){event.stopImmediatePropagation();event.target.checked=!event.target.checked;notice('Custom policy changes require Full edition.');}},true);
async function initializeDesktop(){
 try{
 await window.AgentTrapAuth.ready;const cfg=window.AgentTrapDesktop.config;
 document.getElementById('trial-clock').textContent=cfg.full?'Full · Hackathon evaluation':'Desktop Trial · 5 analyses / 3 checks';document.getElementById('trial-auth').textContent=window.AgentTrapAccount?.state?.email||'Local device workspace';
 if(!window.AgentTrapConsole)await new Promise(resolve=>window.addEventListener('agenttrap-console-ready',resolve,{once:true}));
 const hooks=window.AgentTrapConsole;hooks.labels.connections='AI pairing & alerts';hooks.labels.activity='Browser activity';
 const nav=document.querySelector('.sidebar nav');for(const [id,label]of [['connections','AI pairing & alerts'],['activity','Browser activity']]){const a=document.createElement('a');a.href='#'+id;a.dataset.page=id;a.textContent=label;nav.insertBefore(a,nav.lastElementChild);}
 const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const pageHead=(title,description)=>`<div class="page-head"><div><div class="eyebrow">DESKTOP GOVERNANCE</div><h1>${title}</h1><p>${description}</p></div></div>`;
 hooks.renderers.connections=()=>pageHead('AI pairing & alerts','Consent-based observation in Chrome or Edge. No provider passwords are collected.')+(cfg.full?`<div class="grid2 grid-equal"><div class="card"><h2>Connect the browser companion</h2><p class="note">Install the supplied extension using Extensions → Developer mode → Load unpacked. Select each AI website in the extension and approve access. Your CRM must stay open.</p><button class="btn primary" id="new-pair">Create pairing code</button><p id="pair-code" class="mono" role="status"></p><label class="trial-consent"><input type="checkbox" id="monitor-consent">I consent to recording prompt fingerprints, file names, selected-file hashes, risk signals and request metadata on websites I approve, and sharing these audit observations with my company administrators. Raw prompt and document content is not stored.</label><label class="trial-consent"><input type="checkbox" id="preview-consent">Also share redacted prompt previews (up to 160 characters) with company administrators. Credentials and email patterns are masked.</label><div class="actions"><button class="btn primary" id="monitor-on">Enable monitoring</button><button class="btn" id="monitor-off">Pause</button><button class="btn" id="unpair">Unpair browser</button></div><p id="monitor-state" role="status"></p><p class="note">Supported: ChatGPT, Claude, Gemini, Microsoft Copilot, plus an explicit internal HTTPS domain. Selection and submit intent are observations, not proof of upload or provider use. Existing chat history, mobile apps, other browsers and downstream provider processing are outside this view.</p></div><div class="card"><h2>Phone push notifications</h2><p class="note">Use an authenticated ntfy account and a private topic. Install ntfy on your phone and subscribe to that topic. This is push delivery, not SMS.</p><form id="phone-form"><label>ntfy server<input id="phone-server" type="url" required value="https://ntfy.sh"></label><label>Private topic<input id="phone-topic" required pattern="[-a-zA-Z0-9_]{3,100}"></label><label>Access token<input id="phone-token" type="password" required autocomplete="off"></label><button class="btn primary">Connect phone alerts</button></form><button class="btn" id="test-phone" style="margin-top:16px">Send test notification</button><p id="phone-result" role="status"></p><p class="note">Push credentials stay in memory. Reconnect after restarting the CRM. Desktop alerts appear in this dashboard; native notifications depend on OS permissions and signing. Alerts run only while the CRM is open.</p></div></div>`:`<div class="card"><h2>Available in Full edition</h2><p>The downloadable Trial includes local analysis, asset records, TraceSeal verification and audit export. AI pairing and phone alerts are disabled.</p><a class="btn primary" href="https://agenttrap-ai-governance.arceus6667.chatgpt.site/downloads.html" target="_blank" rel="noopener">Explore Full Hackathon edition</a></div>`);
 hooks.renderers.activity=()=>pageHead('Browser activity audit','Locally stored, hash-chained observations from your paired browser.')+`<div class="card"><div class="actions"><button class="btn" id="refresh-activity">Refresh activity</button><button class="btn" id="export-activity">Export activity evidence</button></div><p id="activity-status" class="note" role="status"></p><div id="activity-list"></div></div>`;
 async function refreshActivity(){const element=document.getElementById('activity-list');if(!element)return;try{const data=await api('activity');document.getElementById('activity-status').textContent=(data.chainValid?'Audit chain verified.':'Audit integrity failure.')+' '+data.events.length+' observations.';element.innerHTML=data.events.length?'<div class="table-wrap"><table><thead><tr><th>Time / platform</th><th>Observation</th><th>Fingerprint</th><th>Risk</th></tr></thead><tbody>'+data.events.slice(-100).reverse().map(e=>`<tr><td>${escape(e.timestamp)}<small>${escape(e.provider)}</small></td><td>${escape(e.kind.replaceAll('_',' '))}<small>${escape(e.fileName||e.characters+' characters')}</small><small>${escape(e.preview||'Preview sharing disabled')}</small></td><td class="mono">${escape(e.fingerprint?.slice(0,20)||'Metadata only')}<small>${escape(e.registeredAsset||'No matching registered asset')}</small></td><td><span class="pill ${e.severity==='HIGH'?'block':'muted'}">${escape(e.severity)}</span><small>${escape(e.signals.join(', '))}</small></td></tr>`).join('')+'</tbody></table></div>':'<div class="empty">No captured activity. Pair your browser and explicitly enable monitoring.</div>';}catch(e){notice(e.message);}}
 async function bind(){if(location.hash==='#activity')refreshActivity();if(location.hash==='#connections'){const status=await api('status');const el=document.getElementById('monitor-state');if(el)el.textContent=(status.monitoring?'Monitoring enabled':'Monitoring paused')+' · '+(status.paired?'Browser paired':'Browser not paired');}}
 document.getElementById('main').addEventListener('click',async event=>{const id=event.target.id;try{if(id==='new-pair'){const result=await api('pair-code',{});document.getElementById('pair-code').textContent=result.code+' · expires in 5 minutes. Enter in extension.';}if(id==='monitor-on'){await api('monitoring',{enabled:true,consent:document.getElementById('monitor-consent').checked,previewConsent:document.getElementById('preview-consent').checked});bind();}if(id==='monitor-off'){await api('monitoring',{enabled:false});bind();}if(id==='unpair'){await api('unpair',{});bind();}if(id==='test-phone'){const result=await api('test-phone',{});document.getElementById('phone-result').textContent=result.delivered?'Push service accepted the notification. Check your subscribed phone.':result.error;}if(id==='refresh-activity')refreshActivity();if(id==='export-activity'){const data=await api('activity');const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='agenttrap-browser-audit.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}}catch(e){notice(e.message);}});
 document.getElementById('main').addEventListener('submit',async event=>{if(event.target.id!=='phone-form')return;event.preventDefault();try{await api('phone',{server:document.getElementById('phone-server').value,topic:document.getElementById('phone-topic').value,token:document.getElementById('phone-token').value});document.getElementById('phone-token').value='';document.getElementById('phone-result').textContent='Connected for this session. Send a test to confirm phone delivery.';}catch(e){notice(e.message);}});
 window.addEventListener('hashchange',()=>bind().catch(e=>notice(e.message)));hooks.render();bind();
 let lastAlert=0;setInterval(async()=>{if(!cfg.full||document.hidden)return;try{const data=await api('activity');const count=data.events.filter(e=>e.severity==='HIGH').length;if(count>lastAlert){notice('Security alert: review suspicious activity in Browser activity.');lastAlert=count;}if(location.hash==='#activity')refreshActivity();}catch{}},5000);
 }catch(e){notice(e.message);}
}
if(document.readyState==='complete')initializeDesktop();else document.addEventListener('DOMContentLoaded',initializeDesktop,{once:true});
})();
